### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [pentestgeek/burpcommander#6]
Hello,

When I run the script don't work, I have this error:

```
Traceback (most recent call last):
        2: from burpcommander.rb:5:in `<main>'
        1: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- celluloid/current (LoadError)

```

Anyone can help me ?

A greeting and thanks

**Comment by angelaruiz0115** [comment]
I also have this issue. I tried bundle install it didn't work.

**Comment by robertofocke** [comment]
comment the line `#require 'celluloid/current'` and add `#require 'celluloid'` and add  space to ```username = options[:username] ? options[:username] : " "
password = options[:password] ? options[:password] : " "```
